[package]
name = "audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#symphonia = "0.5.2"
#fundsp = "0.13.0"
hound = "3.5.0"
itertools = "0.12.1"
num-traits = "0.2.15"
rustfft = "6.1.0"